{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "posthog.fullname" . }}
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  annotations: {{- include "_snippet-metadata-annotations-common" . | nindent 4 }}
    {{- if (eq (include "ingress.type" .) "nginx") }}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
    {{- if (eq (include "ingress.type" .) "alb") }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /_health
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    {{- end }}
    {{- if (and (eq (include "ingress.type" .) "nginx") .Values.ingress.nginx.redirectToTLS "true") }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=30; includeSubDomains";
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.ingress.secretName }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.secretName }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
  {{- else }}
    - http:
  {{- end }}
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-web
                port:
                  number: {{ .Values.service.externalPort }}
          - pathType: Prefix
            path: "/batch"
            backend: &INGESTION
              service:
                name: {{ template "posthog.fullname" . }}-events
                port:
                  number: {{ .Values.service.externalPort }}
          {{- if .Values.capture.ingress.enabled}}
          - pathType: Prefix
            path: "/i/"
            backend:
              service:
                name: {{ .Values.capture.ingress.service.name }}
                port:
                  number: {{ .Values.capture.ingress.service.port }}
          {{- end }}

          {{- if .Values.decide.ingressEnabled}}
          - pathType: Prefix
            path: "/decide/"
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-decide
                port:
                  number: {{ .Values.service.externalPort }}
          - pathType: Exact
            path: "/decide"
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-decide
                port:
                  number: {{ .Values.service.externalPort }}
          {{- else }}
          - pathType: Prefix
            path: "/decide/"
            backend: *INGESTION
          - pathType: Exact
            path: "/decide"
            backend: *INGESTION
          {{- end }}

          - pathType: Prefix
            path: "/e/"
            backend: *INGESTION
          - pathType: Exact
            path: "/e"
            backend: *INGESTION

          - pathType: Prefix
            path: "/engage/"
            backend: *INGESTION
          - pathType: Exact
            path: "/engage"
            backend: *INGESTION

          - pathType: Prefix
            path: "/track/"
            backend: *INGESTION
          - pathType: Exact
            path: "/track"
            backend: *INGESTION

          {{- if .Values.recordings.ingressEnabled}}
          - pathType: Prefix
            path: "/s/"
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-recordings
                port:
                  number: {{ .Values.service.externalPort }}
          - pathType: Exact
            path: "/s"
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-recordings
                port:
                  number: {{ .Values.service.externalPort }}
          {{- else }}
          - pathType: Prefix
            path: "/s/"
            backend: *INGESTION
          - pathType: Exact
            path: "/s"
            backend: *INGESTION
          {{- end }}

          {{- else }}
          - pathType: ImplementationSpecific
            path: "/capture/*"
            backend: *INGESTION
          - pathType: ImplementationSpecific
            path: "/decide/*"
            backend: *INGESTION
          - pathType: ImplementationSpecific
            path: "/e/*"
            backend: *INGESTION
          - pathType: ImplementationSpecific
            path: "/engage/*"
            backend: *INGESTION
          - pathType: ImplementationSpecific
            path: "/track/*"
            backend: *INGESTION
          - pathType: ImplementationSpecific
            path: "/s/*"
            backend: *INGESTION
          {{- end }}
{{- if .Values.ingress.tls }}
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
