{{- define "posthog.ingress.path" -}}
- path: "/"
  pathType: Prefix
  backend:
    service:
      name: {{ .Values.ingress.serviceName | default (include "posthog.fullname" .) }}
      port:
        number: {{ .Values.ingress.servicePort | default 8000 }}
{{- end -}}

{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "posthog.fullname" . }}
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  annotations: {{- include "_snippet-metadata-annotations-common" . | nindent 4 }}
    {{- if .Values.ingress.annotations }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
        {{- include "posthog.ingress.path" $ | nindent 8 }}
  {{- end }}
  {{- else if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname | quote }}
    http:
      paths:
        {{- include "posthog.ingress.path" . | nindent 8 }}
  {{- else }}
  - http:
      paths:
        {{- include "posthog.ingress.path" . | nindent 8 }}
  {{- end }}
{{- end -}}
