{{ if .Values.plugins.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ingestion-cdp-api
  namespace: posthog
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  annotations: {{- include "_snippet-metadata-annotations-common" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 6738
      protocol: TCP
  selector:
    app: {{ template "posthog.fullname" . }}
    role: plugins
{{ end }}