name: Helm Linter

on:
  workflow_dispatch:
  pull_request:
    paths:
      - charts/**
      - .github/workflows/test-lint-helm.yaml
  push:
    branches:
      - main

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloud: ["aws", "azure", "do", "gcp", "other"]
    steps:
      - uses: actions/checkout@v3
      - run: helm lint --strict --set "cloud=${{ matrix.cloud }}" charts/posthog
